### PR TITLE
Replace default Vue.js favicon with normal CircleCI

### LINKED ISSUE #6: This website needs a favicon
It's using the default Vue.js favicon right now. We should customize it. My suggestions, in order:

- orbtoberfest related icon
- hacktoberfest icon
- the normal CircleCI favicon

### PR DESCRIPTION
**Pull request by lex111**
Closes #6

### CODE REVIEW

**Comment by dyegolara** [comment]
Can you add a screenshot of a tab with the new favicon, pls?

**Comment by lex111** [comment]
Sure!

image

**Comment by KyleTryon** [comment]
Sorry, a separate PR has been accepted. Thank you for your contribution!

**Comment by lex111** [comment]
It really puzzles me. Firstly, my PR was created earlier, and secondly, the favicon in Orb-style that you accepted looks a little scary, i.e. I think you just need to use only the crtystal ball, and **not crop** initial image! But okay, this is probably all right for you :(

**Comment by KyleTryon** [comment]
Sorry lex,
The PR is still valid for hacktoberfest. We just have a lot of PRs and only a few maintainers for the month.

**Pull request closed without merging**
