### PR TITLE
Add Orbtoberfest graphic favicons

### LINKED ISSUE #6: This website needs a favicon
It's using the default Vue.js favicon right now. We should customize it. My suggestions, in order:

- orbtoberfest related icon
- hacktoberfest icon
- the normal CircleCI favicon

### PR DESCRIPTION
**Pull request by Nelias**
I replaced all sizes of default favicons with an original orbtoberfest graphic favicons provided in all required sizes as well. I updated manifest.json file and added three og tags in index.html file.

This is how a changed favicon looks like in Safari right now:

Screenshot 2019-10-01 at 23 23 26

This is a favicon's base image:

mstile-150x150

Closes #6

### CODE REVIEW

**Comment by KyleTryon** [comment]
Alt Text

**Comment by KyleTryon** [comment]
Thank you!

Though this was merged. Only the /dist files have been modified. So any subsequent rebuilds will overwrite these changes. Any permanent changes must happen within the /src folder.

**Comment by Nelias** [comment]
@KyleTryon on Chrome where I opened the website before (https://hacktoberfest.circleci.com) I still have the default Vue favicon simply because it is cached in the browser's memory. On Safari where I never opened it before the favicon comes from the static (not generated) public folder and it is displayed correctly as Orbtoberfest graphic.

image

**Comment by Nelias** [comment]
@KyleTryon In Chrome where I opened the website before (https://hacktoberfest.circleci.com) I still have the default Vue favicon simply because it is cached in the browser's memory. In Safari where I never opened it before the favicon comes from the static (not generated) public folder and it is displayed correctly as Orbtoberfest graphic. New favicon also works in my phone's Chrome browser and Samsung Internet browser. It is also displayed correctly when I add it to my homescreen (PWA feature).

image

**Pull request merged**
